### PR TITLE
Support PowerPC64 LE architecture

### PR DESCRIPTION
**Pull request by runlevel5**
PowerPC64 LE on GNU/Linux runs perfectly too

### CODE REVIEW

**Comment by marc0der** [comment]
I'm curious about how this works, as we don't compile for this target. Please tell us the output of the following as I suspect you are falling back to the legacy bash scripts:

```
$ cat ~/.sdkman/var/platform
```

**Comment by runlevel5** [comment]
```
$ cat ~/.sdkman/var/platform

SDKMAN 5.18.2
```

You are right. I was running the fallback bash version. Having said I can confirm the sdk native can be compiled successfully and individual cli (like `help`, `version`) could be run without giving any error

**Comment by marc0der** [comment]
Great stuff! I'll try to get this working and let you know when it's done so you can test it.

**Comment by marc0der** [comment]
@runlevel5 In the end, it wasn't so simple. Sorry. I would need to build support for this platform throughout our backend. Then, even if we can install the native version, your platform isn't supported by any of our vendors. Most importantly, a Java version isn't currently available on SDKMAN for powerpc64le.

So sadly, at this stage, we won't be able to support powerpc64le unless it gains more popularity.

**Comment by runlevel5** [comment]
@marc0der thanks for the response. I do not think PowerPC64 would ever gain the popularity as that of amd64 or arm64 because its market has always been for the enterprises/big institutions.

I understand the limitation and drawbacks to support this architecture and not every project could afford in doing so.

**Pull request closed without merging**
